spring.application.name=metricservice
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[1].id=metricservice
spring.cloud.gateway.routes[1].uri=lb://metricservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/metrics/**